trigger:
  - main

pool:
  name: Default

steps:
  - script: echo Hello, it's my Azure Devops App
    displayName: 'Run an echo command'

  - script: mvn clean install
    displayName: 'Build with maven'

  - script: java -jar target/mavenfst-0.0.1-SNAPSHOT.jar
    displayName: 'Run a jar file of My mavenfst App'
